utils: Remove unnecessary python macro causing compiler warning
namhyung/uftrace pull request #1271
Opened 2021-05-31 16:53 UTC by kangtegong

This commit removes `PyAPI_FUNC` in `utils/script-python.c`,
which causes compiler warning.

This macro is used only for python script within this file,
and doesn't affect in any way, it's ok to remove.

Fixed: #1268

Signed-off-by: Kang Minchul <tegongkang@gmail.com>

2021-05-31 16:57 UTC, honggyukim requested changes
It doesn't compile. We just remove `PyAPI_FUNC` macro but leaves the declarations for the function pointers. For example,
```
static PyAPI_FUNC(void) (*__Py_Initialize)(void);
```
should be
```
static void (*__Py_Initialize)(void);
```

2021-05-31 18:24 UTC, kangtegong commented
just amended the commit! thanks for feedback :)

2021-06-01 05:50 UTC, namhyung approved these changes
LGTM

2021-06-06 07:03 UTC, namhyung commented
@honggyukim can you approve the change now?

2021-06-06 08:09 UTC, honggyukim approved these changes
Yes, LGTM.

2021-06-07 00:31 UTC, merged